/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.vicker.study.project.reactor

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
    start("mono")
    MonoCreationUsage.execute()
    end()
    start("flux")
    FluxCreationUsage.execute()
    end()
    start("mono operators")
    MonoOperatorUsage.execute()
    end()
}
